services:
  postgres:
    image: 'postgres:15'
    expose:
      - '5432'
    networks:
      - app_network
    environment:
      POSTGRES_USER: 'philing'
      POSTGRES_PASSWORD: 'postgres_password'

  fastapi:
    build: .
    command: bash -c 'while !</dev/tcp/postgres/5432; do sleep 1; done; uvicorn main:app --host 0.0.0.0'
    ports:
      - 8501:8000
    depends_on:
      - postgres
    networks:
      - app_network
    environment:
      DB_URL: 'postgresql+asyncpg://philing:postgres_password@postgres:5432'

networks:
  app_network:
    driver: bridge